#!/bin/sh
# File:  treqsd
#
# Copyright      Jonathan Schaeffer 2009-2010,
#                CC-IN2P3, CNRS <jonathan.schaeffer@cc.in2p3.fr>
# Contributors   Andres Gomez,
#                CC-IN2P3, CNRS <andres.gomez@cc.in2p3.fr>
#
# This software is a computer program whose purpose is to schedule, sort
# and submit file requests to the hierarchical storage system HPSS.
#
# This software is governed by the CeCILL license under French law and
# abiding by the rules of distribution of free software.  You can  use,
# modify and/or redistribute the software under the terms of the CeCILL
# license as circulated by CEA, CNRS and INRIA at the following URL
# "http://www.cecill.info".
#
# As a counterpart to the access to the source code and rights to copy,
# modify and redistribute granted by the license, users are provided only
# with a limited warranty  and the software's author,  the holder of the
# economic rights, and the successive licensors have only limited
# liability.
#
# In this respect, the user's attention is drawn to the risks associated
# with loading,  using,  modifying and/or developing or reproducing the
# software by the user in light of its specific status of free software,
# that may mean  that it is complicated to manipulate,  and  that  also
# therefore means  that it is reserved for developers  and  experienced
# professionals having in-depth computer knowledge. Users are therefore
# encouraged to load and test the software's suitability as regards their
# requirements in conditions enabling the security of their systems and/or
# data to be ensured and,  more generally, to use and operate it in the
# same conditions as regards security.
#
# The fact that you are presently reading this means that you have had
# knowledge of the CeCILL license and that you accept its terms.

# This script starts treqs and registers some information about the
# environment where it is running.

# TODO review this

# source function library
. /etc/rc.d/init.d/functions

# For SELinux we need to use 'runuser' not 'su'
if [ -x /sbin/runuser ]
then
  SU=runuser
else
  SU=su
fi

USER=treqs
PAGSH_PFIX="/usr/afsws/bin/pagsh -c"
export TREQS_HOME=/opt/treqs
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib:/usr/local/log4cxx/0.10.0/lib:/opt/hpss/lib

TREQSPID=`pgrep -x treqs`
case "$1" in
  start)
    echo -n $"Starting treqs: "
    if [ -z $TREQSPID ]; then
      su ${USER} -c "${PAGSH_PFIX} ${TREQS_HOME}/etc/registerInfo.sh &" >> /var/log/treqs/treqs.log #2>&1 < /dev/null
      su ${USER} -c "${PAGSH_PFIX} ${TREQS_HOME}/bin/treqs --config ${TREQS_HOME}/etc/treqs.conf &" >> /var/log/treqs/treqs.log #2>&1 < /dev/null
      [ $? = 0 ] && success start || failure start
    else
      echo -n "already running (pid: $TREQSPID)"
      failure start
    fi
    echo
    ;;
  stop)
    echo -n $"Shutting down treqs: "
    killproc $TREQS_HOME/bin/treqs
    #[ ! -z $TREQSPID ] && \
    #kill $TREQSPID &>/dev/null
    echo
    ;;
  status)
     status treqs
#    [ -z $TREQSPID ] || \
#    echo "TReqs is running [$TREQSPID]"
    ;;
  test)
    [ -z $TREQSPID ] && \
    ${TREQS_HOME}/bin/treqs -c ${TREQS_HOME}/etc/treqs.conf
    ;;
  gdb)
    [ -z $TREQSPID ] && \
    gdb --args ${TREQS_HOME}/bin/treqs -c ${TREQS_HOME}/etc/treqs.conf
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart|status|test|gdb}"
esac
exit 0
