/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fr_in2p3_cc_storage_treqs_hsm_hpss_HPSSBridge */

#ifndef _Included_fr_in2p3_cc_storage_treqs_hsm_hpss_HPSSBridge
#define _Included_fr_in2p3_cc_storage_treqs_hsm_hpss_HPSSBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fr_in2p3_cc_storage_treqs_hsm_hpss_HPSSBridge
 * Method:    getHPSSFileProperties
 * Signature: (Ljava/lang/String;Lfr/in2p3/cc/storage/treqs/hsm/HSMHelperFileProperties;)I
 */
JNIEXPORT jint JNICALL Java_fr_in2p3_cc_storage_treqs_hsm_hpss_HPSSBridge_getHPSSFileProperties
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     fr_in2p3_cc_storage_treqs_hsm_hpss_HPSSBridge
 * Method:    hpssInit
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_fr_in2p3_cc_storage_treqs_hsm_hpss_HPSSBridge_hpssInit
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
