# Execute the JNI executable generated by GCJ
#
# Establishes the environment to execute the executable
#
# @author Andres Gomez

sh ./executeJNIBridgeGcj.sh

# Creates the executable
gcj -c -Wall -o HPSSJNIBridgeTester.o ../src/test/java/fr/in2p3/cc/storage/treqs/hsm/hpssJNI/HPSSJNIBridgeTester.java
gcj --main=fr.in2p3.cc.storage.treqs.hsm.hpssJNI.HPSSJNIBridgeTester -fno-assert -o tester.uexe HPSSJNIBridgeTester.o NativeBridge.o

# Execute.
echo Executing
# This is for HPSS logging (it works from 0 - 7, the three bits)
export HPSS_API_DEBUG=0
# This is for the internal logger (WARN, INFO, DEBUG, TRACE)
export TREQS_LOG=WARN
export LD_LIBRARY_PATH=`pwd`:/opt/hpss/lib/
./tester.uexe
